/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni_md.h"
#include "jni.h"
/* Header for class ch10_classload_jni_JniMain */

#ifndef _Included_ch10_classload_jni_JniMain
#define _Included_ch10_classload_jni_JniMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch10_classload_jni_JniMain
 * Method:    say
 * Signature: (II)I
 */
JNIEXPORT jint
JNICALL Java_ch10_1classload_jni_JniMain_say
        (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
